# Form implementation generated from reading ui file '.\gui_about.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutForm(object):
    def setupUi(self, AboutForm):
        AboutForm.setObjectName("AboutForm")
        AboutForm.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        AboutForm.resize(640, 497)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutForm.sizePolicy().hasHeightForWidth())
        AboutForm.setSizePolicy(sizePolicy)
        AboutForm.setAutoFillBackground(False)
        self.logo = QtWidgets.QLabel(parent=AboutForm)
        self.logo.setGeometry(QtCore.QRect(0, 0, 641, 411))
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(parent=AboutForm)
        self.label.setGeometry(QtCore.QRect(10, 420, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=AboutForm)
        self.label_2.setGeometry(QtCore.QRect(10, 460, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=AboutForm)
        self.label_3.setGeometry(QtCore.QRect(10, 440, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(AboutForm)
        QtCore.QMetaObject.connectSlotsByName(AboutForm)

    def retranslateUi(self, AboutForm):
        _translate = QtCore.QCoreApplication.translate
        AboutForm.setWindowTitle(_translate("AboutForm", "Form"))
        self.label.setText(_translate("AboutForm", "This software is fully open-source and free of charge."))
        self.label_2.setText(_translate("AboutForm", "Terraria logo and naming is a registered trademark of Re-Logic, Inc."))
        self.label_3.setText(_translate("AboutForm", "Brought to you by vledd and Giisuka."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AboutForm = QtWidgets.QWidget()
    ui = Ui_AboutForm()
    ui.setupUi(AboutForm)
    AboutForm.show()
    sys.exit(app.exec())
